name: Terraform CI/CD - Dev/Test

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        working-directory: ./environments/dev
        run: terraform init

      - name: Terraform Fmt
        working-directory: ./environments/dev
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./environments/dev
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./environments/dev
        run: terraform apply -auto-approve tfplan

      - name: Checkov Security Scan
        run: |
          pip install checkov
          checkov -d .
